### ISSUE TITLE
Error in tcpypi installation 

### ISSUE THREAD

**Issue by msnaidu7** [dgilford/tcpyPI#44]
Hi @dgilford 
I started the installation of tcpypi it is successfully installed after that, I type 
$python setup.py install 
its shoi]wing 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tcpypi 1.3.4 requires numpy==1.19.5, but you have numpy 1.22.3 which is incompatible.

Give me the solution for this.
Thanks!

**Comment by dgilford** [comment]
Linking to #47 , where I am addressing this now.
