### ISSUE TITLE
Rename pyPI to tcpyPI?

### ISSUE THREAD

**Issue by jbednar** [dgilford/tcpyPI#5]
Nice package! I see that it's called [tcpypi on pip](https://pypi.org/project/tcpypi/1.3.2), presumably because [PyPI is already a package on pip](https://pypi.org/project/pypi). Given that the Python world is so familiar with PyPI as being a package repository, wouldn't it make sense to choose a different name for this project? tcpyPI seems not to be used for any other packages that I can see...

**Comment by dgilford** [comment]
Hi James, thanks for this suggestion! I've definitely considered renaming the package.
The original naming was an oversight on my part. I wrote the name of the package and got fairly far along in development (several versions) before I realized the overlap with PyPI.
I would need to figure out a strategy for how to systematically rename it across each platform/document, but it could be done I think.

**Comment by jbednar** [comment]
Makes sense. Github at least is very good about renaming; if you rename the project, visits to the old one (unless reused for some other project) still work and go to the new one, and old clones of the source code still keep working (with warnings.  Installed packages (conda and pip) are more of an issue, but the longer you wait the more users will be affected, so it won't get any better later... :-/

**Comment by dgilford** [comment]
Project has been renamed to "tcpyPI", although I still use pyPI throughout much of the documentation to refer to the project (for short). The package directory, along with notebooks, utility files, and documentation have all been updated to reflect the name change. A new version will reflect the name change. Thank you for your suggestion @jbednar !

**Comment by dgilford** [comment]
Project has been renamed to "tcpyPI", although I still use pyPI throughout much of the documentation to refer to the project (for short). The package directory, along with notebooks, utility files, and documentation have all been updated to reflect the name change. A new version will reflect the name change. Thank you for your suggestion @jbednar !
