### ISSUE TITLE
Pinned versions of xarray, numba, numpy

### ISSUE THREAD

**Issue by ktyle** [dgilford/tcpyPI#6]
Hi @dgilford I just found out about this package via your post to the TC list! I notice that the versions of xarray, numba, and numpy are set to exactly 0.15.1, 0.48.0, and 1.18.1 respectively. I am just rolling out a new Python 3.8 environment for my department and would love to include this package, but this new environment uses 0.16.2, 0.52.0 and 1.19.5. Are there any test scripts/notebooks that could be run to see if tcpyPI will work ok with these updated libraries?

Thanks, Kevin

**Comment by dgilford** [comment]
Hi @ktyle ,
Thanks for reaching out, and glad you found it and want to integrate it!

This is a great question, and one I haven't given much thought to (apologies!). I want to at some point create a set of test scripts that run every time the code is updated (to verify everything), but I haven't had a chance to.

A quick way to test would be to download the /notebooks/ directory and run those with your environment. If you get similar/close results then everything should be working. I would suspect it should be backwards compatible, but it likely depends on the specific versions/changes made in each module.
**Could you try this and let me know what you find?** I'd be very happy to work through this with you.

**Comment by dgilford** [comment]
@ktyle This should be resolved. 👍
